# Generated by Django 3.2.24 on 2024-02-17 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(unique=True, verbose_name='Link')),
                ('address', models.CharField(max_length=255, unique=True, verbose_name='Address')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('state', models.CharField(max_length=2, verbose_name='State')),
                ('zipcode', models.CharField(max_length=255, verbose_name='zipcode')),
                ('bathrooms', models.FloatField(default=None, null=True, verbose_name='Bathrooms')),
                ('bedrooms', models.FloatField(verbose_name='Bedrooms')),
                ('year_built', models.IntegerField(blank=True, null=True, verbose_name='Build Year')),
                ('tax_year', models.IntegerField(default=None, null=True, verbose_name='Tax Year')),
                ('tax_value', models.FloatField(default=None, null=True, verbose_name='Tax Value')),
                ('home_size', models.IntegerField(default=None, null=True, verbose_name='Home Size')),
                ('lot_size', models.IntegerField(default=None, null=True, verbose_name='Lot Size')),
                ('area_unit', models.CharField(default='SqFt', max_length=255, verbose_name='Area Unit')),
                ('home_type', models.CharField(choices=[('SINGLE_FAMILY', 'SingleFamily'), ('MULTI_FAMILY', 'MultiFamily2To4'), ('VACANT_RESIDENTIAL_LAND', 'VacantResidentialLand'), ('CONDO', 'Condominium'), ('APARTMENT', 'Apartment'), ('DUPLEX', 'Duplex'), ('MISCEKLLANEOUS', 'Miscellaneous')], max_length=255, verbose_name='Home Type')),
                ('estimate_amount', models.IntegerField(default=None, null=True, verbose_name='Estimate Amount')),
                ('estimate_last_update', models.DateField()),
                ('market_price', models.CharField(max_length=255, verbose_name='Area Unit')),
            ],
        ),
        migrations.CreateModel(
            name='SaleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_date', models.DateField(null=True)),
                ('sale_date', models.DateField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.home')),
            ],
        ),
        migrations.CreateModel(
            name='RentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_price', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rent Price')),
                ('rent_estimate_price', models.IntegerField(default=None, null=True, verbose_name='Rent Estimate')),
                ('rent_estimate_last_update', models.DateField(null=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.home')),
            ],
        ),
    ]
