# Generated by Django 3.2.16 on 2022-11-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_unit', models.CharField(max_length=100)),
                ('bathrooms', models.DateTimeField(verbose_name='date published')),
                ('bedrooms', models.IntegerField(max_length=100)),
                ('home_size', models.CharField(max_length=100)),
                ('home_type', models.CharField(max_length=100)),
                ('last_sold_date', models.DateField(verbose_name='last sold date')),
                ('last_sold_price', models.IntegerField(max_length=100)),
                ('price', models.IntegerField(max_length=100)),
                ('property_size', models.IntegerField(max_length=100)),
                ('rent_price', models.IntegerField(max_length=100)),
                ('rentzestimate_amount', models.IntegerField(max_length=100)),
                ('rentzestimate_last_updated', models.DateField(verbose_name='rentzestimate last updated')),
                ('tax_value', models.IntegerField(max_length=100)),
                ('tax_year', models.DateField(verbose_name='tax year')),
                ('year_built', models.DateField(verbose_name='year built')),
                ('zestimate_amount', models.IntegerField(max_length=100)),
                ('zestimate_last_updated', models.DateField(verbose_name='zestimate last update')),
                ('zillow_id', models.IntegerField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField(max_length=50)),
            ],
        ),
    ]
