# Generated by Django 3.2.16 on 2022-11-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='last_sold_price',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='property_size',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='rent_price',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='rentzestimate_amount',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='tax_value',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='zestimate_amount',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='zillow_id',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='zipcode',
        ),
        migrations.AlterField(
            model_name='listings',
            name='bathrooms',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
