# Generated by Django 3.2.16 on 2022-11-21 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221121_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='bathrooms',
        ),
    ]
