# Generated by Django 3.2.16 on 2022-11-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20221121_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='bathrooms',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='listings',
            name='last_sold_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listings',
            name='rentzestimate_last_updated',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listings',
            name='tax_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listings',
            name='year_built',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listings',
            name='zestimate_last_updated',
            field=models.IntegerField(default=0),
        ),
    ]
