# Generated by Django 3.2.16 on 2022-11-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20221121_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listings',
            name='area_unit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listings',
            name='bathrooms',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='bedrooms',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='listings',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listings',
            name='home_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listings',
            name='home_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listings',
            name='last_sold_date',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='listings',
            name='last_sold_price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='listings',
            name='link',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='listings',
            name='price',
            field=models.IntegerField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listings',
            name='property_size',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='listings',
            name='rent_price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='listings',
            name='rentzestimate_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='listings',
            name='rentzestimate_last_updated',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='listings',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listings',
            name='tax_value',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='listings',
            name='tax_year',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='listings',
            name='year_built',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='listings',
            name='zestimate_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='listings',
            name='zestimate_last_updated',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='listings',
            name='zillow_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='listings',
            name='zipcode',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
