# Generated by Django 3.2.16 on 2022-11-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20221121_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='bedrooms',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listings',
            name='last_sold_price',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listings',
            name='price',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listings',
            name='property_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listings',
            name='rent_price',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listings',
            name='rentzestimate_amount',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listings',
            name='tax_value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listings',
            name='tax_year',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listings',
            name='year_built',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listings',
            name='zestimate_amount',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listings',
            name='zillow_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listings',
            name='zipcode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
